//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ingredient")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: Uuid,
    pub unit_id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::unit::Entity",
        from = "Column::UnitId",
        to = "super::unit::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Unit,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(has_many = "super::ingredient_quantity::Entity")]
    IngredientQuantity,
    #[sea_orm(has_many = "super::ingredient_sort::Entity")]
    IngredientSort,
}

impl Related<super::unit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Unit.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::ingredient_quantity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngredientQuantity.def()
    }
}

impl Related<super::ingredient_sort::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngredientSort.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
